name: Release mosdns docker

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**'
    - 'lists/**'
    - '*.txt'
    - '*.yaml'
    - '*.conf'
    - '*.txt'
    - '*.sh'
    - '*.py'
    - 'README.md'
  schedule:
    - cron: '15 17 * * *'

jobs:
  build-docker:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --detach -a blockdns --remote-only --no-cache && flyctl regions set sin -a blockdns
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
